CREATE DATABASE IF NOT EXISTS music_project;
USE music_project;

CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PICTURE_URL VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TOP_ARTISTS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SPOTIFY_ID VARCHAR(100) NOT NULL UNIQUE,
    USER_ID INT NOT NULL,
    ARTIST_NAME VARCHAR(255) NOT NULL,
    PICTURE_URL VARCHAR(255),
    FOLLOWERS INT NOT NULL,
    RANKING INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE TOP_MUSICS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SPOTIFY_ID VARCHAR(100) NOT NULL UNIQUE,
    USER_ID INT NOT NULL,
    TRACK_NAME VARCHAR(255) NOT NULL,
    ARTIST_NAME VARCHAR(255) NOT NULL,
    ALBUM_COVER_URL VARCHAR(500),
    RANKING INT NOT NULL,
    DURATION_MS INT NOT NULL,
    POPULARITY INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);


CREATE TABLE TOP_GENRES (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    GENRE_NAME VARCHAR(100) NOT NULL,
    SCORE INT NOT NULL,
    PERIOD VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

