CREATE DATABASE IF NOT EXISTS music_project;
USE music_project;

CREATE TABLE USERS (
    ID_USERS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PICTURE_URL VARCHAR(500),
    PASSWORD_HASH TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TOP_ARTISTS (
    ID_ARTIST INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ARTIST_NAME VARCHAR(255) NOT NULL,
    PICTURE_URL VARCHAR(255),
    RANKING INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID_USERS) ON DELETE CASCADE
);

CREATE TABLE TOP_MUSICS (
    ID_MUSIC INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    TRACK_NAME VARCHAR(255) NOT NULL,
    ARTIST_NAME VARCHAR(255),
    ALBUM_COVER_URL VARCHAR(500),
    RANKING INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID_USERS) ON DELETE CASCADE
);


CREATE TABLE TOP_GENRES (
    ID_GENRE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    GENRE_NAME VARCHAR(100) NOT NULL,
    SCORE INT NOT NULL,
    RANKING INT NOT NULL,
    PERIOD VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID_USERS) ON DELETE CASCADE
);


DELIMITER //

CREATE PROCEDURE REGISTER_USER(IN p_username VARCHAR(100),IN p_email VARCHAR(100),IN p_password_hash TEXT)
BEGIN
    INSERT INTO USERS (USERNAME, EMAIL, PASSWORD_HASH)
    VALUES (p_username, p_email, p_password_hash);
END //

DELIMITER ;


DELIMITER //

CREATE PROCEDURE LOGIN_USER(IN p_email VARCHAR(100),IN p_password_hash TEXT)
BEGIN
    SELECT ID_USERS
    FROM USERS
    WHERE EMAIL = p_email AND PASSWORD_HASH = p_password_hash;
END //

DELIMITER ;
